name: UI Tests CI

# Run workflow on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build -t automationexercise-ui-tests:latest .

      # 3. Create folder for Allure results
      - name: Create Allure results folder
        run: mkdir -p allure-results

      # 4. Run tests inside Docker
      - name: Run tests in Docker
        run: docker run --rm \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          automationexercise-ui-tests:latest

      # 5. Upload Allure results as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
